apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# - github.com/argoproj/argo-rollouts/manifests/crds?ref=v1.0.6
# - github.com/argoproj/argo-rollouts/manifests/base?ref=v1.0.6
# - github.com/argoproj/argo-rollouts/manifests/role?ref=v1.0.6
- https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/install.yaml
resources:
#- namespace.yaml
#- clusterrolebinding.yaml
#- github.com/argoproj/argo-rollouts/manifests/crds
#- github.com/argoproj/argo-rollouts/manifests/base
#- github.com/argoproj/argo-rollouts/manifests/role
#- github.com/argoproj/argo-rollouts/manifests/dashboard-install
namespace: argo-rollouts
transformers:
   - annotations.yaml
   - labels.yaml
