apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: k8s-demo-app-ci

spec:
  entrypoint: k8s-demo-app-ci
  arguments:
    parameters:
    - name: repo
      value: https://github.com/slavic-viking/k8s-demo-app.git
    - name: revision
      value: 'v0.0.1'

  templates:
  - name: k8s-demo-app-ci
    steps:
    - - name: checkout
        template: checkout
    - - name: build
        template: build

  - name: checkout
    inputs:
      artifacts:
      - name: source
        path: /src
        git:
          repo: "{{workflow.parameters.repo}}"
          revision: "{{workflow.parameters.revision}}"
    container:
      image: alpine/git
      workingDir: /src
      args:
        - clone
        - --depth
        - "1"
        - --branch
        - "{{workflow.parameters.revision}}"
        - --single-branch
        - "{{workflow.parameters.repo}}"
  
  - name: build
    inputs:
      artifacts:
      - name: source
        path: /src
    container:
      image: gcr.io/kaniko-project/executor:debug
      args:
      - --context=dir:///src
      - --destination=slavicviking/k8s-demo-app:tests
      - --verbosity=trace
      volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker/

    

