---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  serviceAccountName: workflow
  templates:
  - name: build-kaniko-git-tag
    inputs:
      parameters:
      - name: repo_url
      - name: repo_ref
        value: refs/heads/master
      - name: repo_commit_id
        value: HEAD
      - name: container_image
    container:
      image: gcr.io/kaniko-project/executor:debug
      args:
      - --context={{inputs.parameters.repo_url}}#{{inputs.parameters.repo_ref}}
      - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.repo_ref}}
      - --verbosity=trace
      volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker/