apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: github-ci
  namespace: workflows
spec:
  serviceAccountName: workflow
  arguments:
    parameters:
      - name: repo_url
        value: https://github.com/slavic-viking/k8s-demo-app.git
      - name: repo_ref
        value: main
      - name: repo_commit_id
        value: HEAD
      - name: container_image
        value: slavicviking/k8s-demo-app
      - name: container_tag
        value: latest
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            template: clone
            arguments:
              parameters:
                - name: repo_url
                  value: "{{workflow.parameters.repo_url}}"
                - name: repo_ref
                  value: "{{workflow.parameters.repo_ref}}"
                - name: repo_commit_id
                  value: "{{workflow.parameters.repo_commit_id}}"
          - name: build-kaniko
            template: build-kaniko
            arguments:
              parameters:
                - name: container_image
                  value: "{{workflow.parameters.container_image}}"
                - name: container_tag
                  value: "{{workflow.parameters.container_tag}}"
            depends: "clone"
    - name: clone
      inputs:
        parameters:
          - name: repo_url
          - name: repo_ref
      container:
        image: alpine/git
        volumeMounts:
          - mountPath: /work
            name: work
        workingDir: /work
        args:
          - clone
          - --branch
          - "{{inputs.parameters.repo_ref}}"
          - "{{inputs.parameters.repo_url}}"
    - name: build-kaniko
      inputs:
        parameters:
          - name: container_image
          - name: container_tag
      volumes:
        - name: regcred
          secret:
            secretName: regcred
      container:
        image: gcr.io/kaniko-project/executor:debug
        args:
          - --context=dir:///work/k8s-demo-app
          - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
        volumeMounts:
          - name: work
            mountPath: /work
          - name: regcred
            mountPath: /root/.docker/
