---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  serviceAccountName: workflow
  templates:
  - name: clone
    inputs:
      parameters:
       - name: repo_url
       - name: repo_ref
    container:
      volumeMounts:
        - mountPath: ../work
      image: alpine/git
      workingDir: /work
      args:
        - clone
        - --deph
        - "1"
        - branch
        - "{{inputs.parameters.repo_ref}}"
        - single-branch
        - "{{inputs.parameters.repo_url}}"

  # - name: build-kaniko-git-tag
  #   inputs:
  #     parameters:
  #     - name: repo_url
  #     - name: repo_ref
  #       value: refs/heads/master
  #     - name: repo_commit_id
  #       value: HEAD
  #     - name: container_image
  #     - name: container_tag
  #   container:
  #     image: gcr.io/kaniko-project/executor:debug
  #     args:
  #     - --context={{inputs.parameters.repo_url}}#{{inputs.parameters.repo_ref}}#{{inputs.parameters.repo_commit_id}}
  #     - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
  #     - --verbosity=trace
  #     volumeMounts:
  #       - name: regcred
  #         mountPath: /kaniko/.docker/