apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cicd
  source:
    path: argo-events/overlays/cicd
    repoURL: https://github.com/slavic-viking/one-cluster-army.git
    targetRevision: OCA-5-cicd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: true