apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core
  source:
    path: ''
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: '5.4.1'
    chart: external-dns
    helm:
      parameters:
        - name: provider
          value: ovh
        - name: ovh.secretName
          value: ovh
        - name: policy
          value: sync
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
