apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core
  source:
    path: ''
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: '3.35.0'
    chart: ingress-nginx
    helm:
      parameters:
        - name: controller.metrics.enabled
          value: "true"
        - name: controller.metrics.podAnnotations.'prometheus\.io/scrape'
          value: "true"
        - name: controller.metrics.podAnnotations."prometheus\.io/port"
          value: "10254"
        - name: controller.metrics.serviceMonitor.enabled
          value: "true"
        - name: controller.metrics.serviceMonitor.additionalLabels.release
          value: kube-prometheus
        - name: controller.metrics.serviceMonitor.namespaceSelector.any
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
