---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    github:
      owner: slavic-viking
      repository: k8s-demo-app
      webhook:
        endpoint: /github
        port: "12000"
        method: POST
        url: https://webhook.wostal.systems
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      # webhookSecret:
      #   name: github-secret
      #   key: secret
      insecure: false
      active: true
      contentType: json
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webhook-ingress
  namespace: argo-events
  annotations:
    external-dns.alpha.kubernetes.io/hostname: webhook.wostal.systems
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - webhook.wostal.systems
    secretName: eventsources-tls
  rules:
  - host: webhook.wostal.systems
    http:
      paths:
      - path: /github
        backend:
          serviceName: github-eventsource-svc
          servicePort: 12000
