apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argo-events
spec:
  encryptedData:
    secret: AgA3aKm+2MQ19YaAEU4WLfFf8h2/mYHqBXA+nWqGttod40Z67vIGyPtphWKLlsupM55phDnjQJkhl9XfG4HQqXrdscanSWR55tOrdGD1vNzadCgLeTIDcoA3xp/bkumIUiKhLwDYVlXUiYDLn2izBp3RAiIuUM29ra6iABwIDgn2iWR+cN63H/95u0hZ1zKNsu05GnvNPmu0Wykpjr2qjYfKtPAbfQN94lwNxu9d5dVAqb6MXglEQ+w5EvPE4w2T9Hl8cdKNEKEXMPaeH8L1jfi2FQkmopIa/3ZdRBX45k1dtsFixH0l1Z8duPdkv8kmyjBqidexiuFJthrazUgkiRY8BB/GOxnOdaPlIgQOtXNczA7qib+VUS14pY2nFxwOyySzLcoqLcyUrz7T7hU7w2rcmst68nml3OTPAooWd4gvUWTwJuGkb7SUEyi4j9VVPHJ1oIYdrOy+uxhe5PyC87LmzQWUTMfGDPY76RYbjcIV5Vav8ojB5BbdvUzEOhywhFJ+iXEQPz1RCeIQ1BbF2+YW+kBOUdS+rQIhpZTIGy34UIEehfXgxn/8oltFYe9trf+S+VOevGf1QrEsjVl+PvPj4Rqx+ybw+jGJuvUdRB0MIA28iJ5cN5dyvm6VWqc6PAgbt4M0nRo0CVDggEsDFnW9SHLjrrKEI39wg5/AFxllRs6oJNFKEtpfSw9rWh42Ifo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argo-events

