apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBUOM9BRJ5wUpBXdod5guAqovSXwqfQ5bYeVeQL3LbjrEE9P6lE7uK66rDId2Ph8OYvThozvCzcNsH/aaQrQOjIbcdnfdxDvTfHOfdHiE/45Kjjlk+30bP7qkZYFWMYMgnzvhyMzuGL2JNjBN+MwOIj0NMsuVviWnjg8nSPH1Fo4LS0zGpPR7hUdopL+yzBMyeFSKHCL/u3rRdbp+mrTqiQv4nbnGkkNEwwEk7mzKtbQT5VTE/poKYNPFVz2piUmXaBvmPBX2YJeuuoAIxiRHJ0W4qL5a4EwWkEWpmhdIMZKDZDqk01m2N21UsQuRaNljYdY049pkcgaI4Rdf9I83D5hv614FQuRaSEGfOaNjC8jExZ48/5vHkDZqEtFTaXpIYYm90xVRQlAYDVqBuuF7I1xv9W/d+K5KKYPRVJyR6K7stLYqpC1mjIxLlRJodzGBguaLOwqHOCq+a6G4NUvxbVs+VaYU2F7EOqz1kBw9WcFK4ES+TJvku8Bqu/r9TA1AofLii3KuDgIT6nSURDAMH9YTYW16abi5k2VLhvfyGBO+WRFxi3DkTI/sLLi29y43zRDv7/LqvMrBVpuKPVSDPlv9x5h9pHsYJTgTc80oXvv5o+QVDCg5/wFG6+fkL0O/iOwX/zXYsE6KCMtKXiNUAYd2xhqJTxEBam1dvj49r8znXMH0pjrLNIps297GDFwUXbsk6e1K3Sftkgk5dzkzJhX+dGozHzfduvK6DgI3uRRLO7u+B2gvTy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

