apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAVP4BpcgvvYOCpISmeCveOEV5Ymz+VzXZmNPAoiLAF/7UrTN5fSiDwupHIea2LBq+Pd7wmcqSMlexDJsinMSXDlQoSJoCIBr70HYt0rJwIX4koQZ7raUEZ9mVXYYkW5CmEyjCcjkyLld2cA9v3i3ukqxYbR7Y7Sx6yLATzTdDTBGM6pbScxRa/sym/QeQgFNq72SY7Zrx+iS436rQkWW/QQQ6tVq7rh0AheC/M+NpuK4Xrc1qDw9nfsse23JEj7XWTzcioDpQ/d58ALuDI5Ov4Yb4s2/8AwEsE9z+M8nZEnc7R7Y3Q+exoQPH0kggQT325idgYX91u5vVh9WRAAfsyssrtOpY7rv3EbJLUT7fdmD0xHIcdKynME7OfJrkeTLV2DULvthu7SJlRBxCRRu6veEscUvc9VUcjUyGP5+fQFMza0IUAQNWLubLrsZVTzhVuj3KXeqlrmDlY16DOL5o0SmvspbpbMpQ8wU6Um5VbqHBQkwCP1YWAhztyo9j2X3oEnONYx4dea2JUJzy3fNxi2Z9H7psqN7OfXiOCrC/pQygTlPNhe3LFvCCVVbqBFn+H+cFhSBiJS/EaAx8tqT7ZCIg117/BuA9OWoqOfxrN7Grh62TVK2byBBC84nyKJojPxGMbdJNGwJAY/+J74epKYIFL9T4GWbcfGVXe83djLroWdFtzb2QI4we+/018cFSAxBXreEJfkioWQeR5uWsdhSFGp3013lKgAU62iaYZ6JlyNCfBOmUx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

