apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBH69EiAxNF29aJxKuJS/z/ZRdqfDR82VKFpOOub+rQ6ezpas4RwlrPfjXTm2qX9N0E+gprNmCtWYoBVsInFho9D6Pxm0zBy5xclLrP3lQisjBpBPoC5h/L/Nqeh9F+Lx25OG6h5lujDyGtJ9NhsbW/hhucg6kQQcUfdoiRpMpnPwPaPAf4WV+pchyV0bVFK6SS/hoSVNlzWpoAJUnRjU+wytRF7k/X2AUXnOecsXgpMHMI9PtQlCl2txLguM1j2F9Ag5rOOvEBAhaZc0xc+lwPmOHwN26Cx4e/yZAVWCSvX2hTNLwUUvEEQFgHCIK6G7Krd+3GS4wmNhgZQTF6aP2ckjG5lKt/yZU3DOMq1ba3M9LGQ89G5MCU/1hIFKUMB+j8bQw3OzVZBWZyUDUgMhOms4iYQW0iwOLZI4kMjn3LTM6G1KKr9aa/lXjaf/YDePfZMPJ030iQgjDDU6vVEayNUAOEErh5Ip3bYscDPnE6UpNhBBOOFHErCdC+OlKI4t69ohMJ0RhtzlSbTna7Gc17r0QC2BdMjc63x9jMvWiTqZdKvTEWqr76QGGw4WMonV+ONwEhJxqDsAUduaKMydiqHauc9zr7+3vEL15Rgq3ny8hcTULgr7LBqWrwU+rVA7oCcWuY7Xbxc0OC1g2Qj+MROSNzw5lNh6T+NWazPwN2JSzzcRAMQKxMho42RoEEJ5o=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

