apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argo-events
spec:
  encryptedData:
    secret: AgBVxPYJ7/NoSTa3kbUz7vdHeJ2/lQe4zj1UE8UFnYFHwP79GoPM8YBNFNJ2c6/c8ytHRspjxhtUtMOgIjURHweVIQ4j2CmcuCa4rEGSw/l5LBoC5nKls0Piq5P7zSx7t647W1fwRlKQwS20/Q0j2L+h4hzD5BRuChWsPM6PbfzUjJg5DX7NatZP9coqSE8rBpRkE4X2W6r5l5yCKDjIwAF6tQeTny2CIiC3mxY+ZkTGTa1a7GnQdbVFPuSFeoRIqYqazn+OrA/BstgC3OJRyCpn4MQVb72+Jt3lXJJhSoZ2F/OC3mvMohbgRLok1PsIN5gWxosZ74NRqitZyOxuCJrQo+FsUYBPj9UuOz/kak/uyuaw6J8DBwhOea4LcPhBG63XQICPgWT/IAeEaux/J1nAkYPhQ6JscjpqAErmvzE84DWHYQWwnnUM8Z4a3pRSwAVfE5n4NPgjqBDaItGH0VlTrTL4VkOtyOzCaDadl8BEIgv7ypMg/IdBpZAcnFJAww0EF3YO2tw279Q/Sxv3BUv3cvqWONbE6XPJ5419tpZ1nUFG7BgcKMTsrCyXWsDgvscCyasvPaji6QukHFyPSAlrM61UXm+vMzwntLhi86GNRO+mI9B9vAO7LRU+HK1XKBcZEfyCIS5+nPpLBoQmOURDd7JslrFbwS63nJvz00rqebvBCyDa2qLTXthPWabaGqpqveRIUtbE/23QvX4PZg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argo-events

