apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgC6GWKuy2/rf9ZUip9HrIX32EwhisSZcx9apmlFHw+peDOyZrjZqFDc3B+Jnvijv3ew+TPbvI3rK0dhbtOaKiRBMUIACpTj19PXf0Kaf2gM8SXzp8yNUPA8CfCBG6jVJcaLrW6i1U2lU0kzxo12s9D1d55rNWss6iZl6mTn9GokH4i6RWusElmgz2mib69BzaIzU7Nna4VJaQgrUqHqMjQkIfppWQOP6JtGsfg+4vTYf0RDfd2SINEZo0YR5zQrg0UaIce7SFnF9g6QRfIXC113xsuLPJZ+XY60Uy0b+fFJC8KLvD3ue3UGRV8Rg3ebP//nOitWk2fYTs8IqjcTtmpp/GlKejk5fj5Trk5/L0njX3s2+T+eTlgTBr4/BU1lz3vnyV0U77maCFV8u6r/OAXrzpzbvSNI42w8t/Bho634BJ9RwKD/56BrlM9jy2eKZrt6UuHrx/axGo1U1N/PVnjC235sEFT8S/eQmvi76ZiV+Y60OkY2IzfDSkr2JKOY5rSCcnUqlCH/C7116TdlyId9yf/BWF6O7fWpv1b7rTMiSANinHH0erwi3ZAORwGUVxb3lXDLp99h0iCP9PcSSaclhkpQICaWShIf4fsaKRWDxnC3Q15+0TOMepyKjUjhD1J387ZZ4/0b47iVxIYnplt2ecOFFjyiDgdfAEQsU3J3dXxLYr9oj+hYqaH0KhqswizZ5as+098MSEhapV9xSC3izBtUtIhOB3LFHNhLVeeslILnFVv0USc+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

