apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgC1aL+V8c8FofGT3jrNBCqJkQMxtz2cm61M10jx39BvzFnb90d+DPXmrnBnH8GE3sUUHERd9qWEFUnF2PCJxMNWrxv8bKV627/2IbfmCbNjZBQ5xdoakrJHjs5U++OKIGNA37vRsGykCceEAhnlkxW0thYMDZCDJVSmwk7fJVW/eWfR+RJrWBo15JNCq9k7YzZF5zwNHeCKoY26hX2WFXAx7ZFG6OCW6oMDXMdvCeg7/SCk4Www5yiUZ7XWvZ4wvmPrDNk932m3TeHOi5xWfN6ysTV9stbECK2vzfJ7wbacMn8FTuQBB4y3X3vSuBYwmNX/1lvR+3zueeYemSulLFRXrcDDaWN9eYZRRXK/hjLLIoUVlQsyS8zJniPQetkxZpY+K4m3aDpcBq6NRiBA8OcivrlJKCE03WsncLLmMm8GhoEjJZ2xuPREpulyzf0WYEIbnAlx4nXMdme3XIG1KmlpVaMuCtN6o7Bo7YWcUKi2kj743rzNP1Ld6f+HHRjI7m5n896cUke5sP3AZDphVQNI0XDqnjZrhK+6S0O+csMDJ8AnXYVqRALL89N7xhw8MXj2Y/4WhK4xLBCmw41pvnshkn5Mg9/KkD/BHTWXVLBfbazVMpfVX//torMcRiODdBEBSsDWxPrPUnwenVE2wMmyKgQgeilEYWGIOrlUNVK3Fb3nNpFp/9YoaSm2mx4DnnSNaBovWWw+eFoS6ddNXCAp6Okz0V3b12W8TLl7M0FH5ekvYqrqCLG5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

