---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: github
    eventSourceName: github
    eventName: github
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: github-ci-
              namespace: workflows
            spec:
              template:
                serviceAccountName: argo-events-sa
              dependencies:
              - name: github
                eventSourceName: github
                eventName: github
              triggers:
              - template:
                  name: trigger
                  argoWorkflow:
                    group: argoproj.io
                    version: v1alpha1
                    resource: workflows
                    operation: submit
                    source:
                      resource:
                        apiVersion: argoproj.io/v1alpha1
                        kind: Workflow
                        metadata:
                          generateName: github-docker-ci-
                          namespace: workflows
                        spec:
                          entrypoint: clone