apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAp2wfYjTh+hQ7vI8nOSP+uxDz7sfUB0FvqW5xV3V+18OfwrHTL1LkC4uq3gBdA7hlnpyVzPU5YzNX3ZXsptazaHAalu6U2KzPFQ2154ldBOAmgq6PvAqEKFuYZjF2TuXvQ31q9MECxoVIa8B5zmytv0UK8CRN3t6OjyvB3Jrks3oEygHOtPEIH9w1AV2W6q1ES1ju8cIdGIcY32Lj2np0f7X2J7rHbqKO9C8rAlJo0wB94qyII2J6nxGnDNYGoL/287rK4F+nQQeSwMVdkYFCc1AoqCRPTV6GxRGpycJm6cqxCDEWoUxTE39R/K/0To+EJ7P/RPhFgPBH5OjI6Nzd5JkWTmloj8Hq+QDgfDieyG1+REvBRni6795/aJaOus6NTeMK6q0sPD4hhfk0Anjk6Ib9urWhc0sq9FZkm2aJVyvKiEXC6WIBssvWahklL8dIXuYg9FLCDI/gSVr8XhuXuCQPTHywmU0+/uP2QcWNQ4LZW4s28XpyvuWWnHbokT/kf3wM4tKpyPB1GvprGik2MBvr4fGEKj+FZ/FR8XLZYAj3+yYB2YX/4Z84YFfqK+qPyk3mzNkugnbrTjCG+cyRQas1BPVbdlhB+5FDYCLaFbztW0dhdeSOir780U9Qi+QGBFp0QhpAVtPLtXXvT2C6rLvaOJZ2b8rZHwhb6fHmfXcFblC4jXjfuq/e/tR0PU6g2IJaF816hjXisNKoI1UIXX4YsoFaXqIE08rJYj2rs4MqbiNjxxuq+Q/ONvwQF2uCiN6rOs4r19pMqaxSMKCwvAFt/Y6NuuE0++rHmfB1ayzpigGCWnmJXOAWRKgi6KcSHSbF8EdudmrV4A4S0ZqE2Zn60O5kH16LKNVZQ1M/xVNHljVqpljJjW2BUVeSD2tcAW6a9vtmwnL1qmHXfMzymBeVFa7nPG9pzVEeaf5ESahtr2LE6bUYIgyMAFLcvFsNBFVAtjHss1GOjFi4IPx9xoQvsRPp24GTcV6n340aehQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

