apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBzAfujY7rOg8Js4VZ4bzET1UcOoi1lD79W2zeI2EOMpqeL+eaNDnz697040vNbiaqBnjo9C6fhdhZUskaxWieG79bz8RrgcKfnjblHAIGnhf8uRgzVYrJY7VtvbdZfZ73RJA1/gFyHEMIFZJWw8kdWH5aZtudF1dR/AoERZ8FsE5gv+k8iYXInAsQspBjboLWgLTL/gDbWCQcGAei1aV2vzor7fywRNrwlrtH2lQJN2rdOB7hBtnfv7qXhkJD3MDZNeMDHNVt+RtqPMlXU2gq58IkxPEEHJ+ZPulP4+jJFmHeWMLIcHG/xn9BmZP6ho5SoYdVz+Cbp/hnbiulIMLA20UqQoYHaC+wJIwXGcxws5Y7zB0nNiCp0AbgCJGwsB01ofyzUynLsj7tnhheEQL+Ym97/hAaI91hZ0dhXj+l3WgomVfRESFautPjW0rZp2mKxuKZhoeqctNtEeoKQ6lAhNwi3cC150XShgHMe8+6MEZwRhtLXVG8colPKO/CMwZZYhDFlFP53P3Q931v6YGeFr91lOLPdoXaEbF85njuNc0PXOx09tUhZU8ObL8dVXUbuPsGyhniwul6IugwTsshQ/02sKWcKJBM1n/OY/CjsLS8/b6W4+9lMik++EilYym0V8lwylxzi7cK0fxtfZtBLL8XNfeyhQIupkFwAS8vbm/6E0c67PabYKl19NetbpGD+TBoi8LygDSNF6i5Q5fwoFoSWhHTNIa4s1yao9xGTnkFvYmNzkfPrdNv4EQvbSAFewr3qx8iUtM6hZXLG+SftM0OlaeoAKbD5Ww8pGmPyxadW5xvceut+bmDwVlGgbjODIat7MxzipsNpTEWFoLcIeIq2ojTaZC4y1t0lUVsL4TDt5J+PeGM5Y/gOPQhrscZOY039pA+ZgauVVIkBUhy/AZctcAw2dxZbe9UlaasW5W81mh1rpXvNR2VvUpuPql7D8gyADeU48HhVGV7OYbwzZxXAZbePiGilTw0e8bLuYw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

