apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBK7BszVpPlrBTJ+EbHeiOtOi2ykwa3aXFZBjq2oLpDbnWFdY7mqiy18K5VQ+r268He6egLWEv9ptu+Q0rha6wW1PHpiwrH1OGPyQS8eAUUrvJDnu10Kw7IiA4QBjSkAVpRd8CpdcjM+qAKcAL9xxCNoPCdf+yQvObLVK0aDqkn/g3QfaSnPJvcDp5xCk/Is/wcDQVAFXniaV/V3yeXZmnhSJ/Ju+HWHV+C/59jn8pZl1rIuV8vt7Rk5c659Y79Plkp+awf/PVAukS2f8fzFmJ3ARWjb5L0T6QNdzpRyzkLLcA1U5fobcwDAmItenKmH9nhCQN11rA6ak3ByY9XKquXHi8tRDvolpsljw4F2NOhak8xhgyiA5a77xYtZ6DwdvNNis6VA3+WXcNeUvRI9be6qJt54g12E/09B4mN2x9xi16Sgih9KH5zSCzIxFyFzv+NbnmXWugE1gCnrr5V2arwg8eGOXJ4Ax6HJAONPVHIIJWdMQuAYps9eb8vbEWD7gXCz+V+aR7M7x/g3K0KXZPUvlEj3L9UdveRX4Qe1L7Roi6fiqvS4ZnCwDvFU4QyNUBxVrnxvwzBZSw3yt/iD1S9zgNLYTaAurO33szcocJvaUjROT/r3GANjESMj86SM2kKrdlRmTa6fMdrDfLdxFxn1i/Y/Ym6D3G1h3NUMYff+nUqWD59KfmgSkcNGymklFh90TW8eC+WOwrVoYsT4g16Q12PL90wuWgqxsGvkQXfiEVVQCLlk+E8EXrnA//j7CXrrBDPs9Pr/3yRSwdTzb3Dwo1uIYDmgekOo421tTpBriNcdoLAbjxQGW6SfQq518c+mHwYuOWRIvZZYIyp2/9YjYxGwqsqRRBEZG7iy9OmQ4eztIJif4fFbLRT/lxSX4hmHCCr3o2asZdCBq8dnxUdgQjvviB1XMhGxsFUEl9MZq9IknD7N9aC4HaLi+6MwNfuiJ7pg8kWMIBMPcJKzi2RVcMHho/PvlqYB/WJBgmmug==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

