apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tick
  source:
    path: ''
    repoURL: https://helm.influxdata.com/
    targetRevision: '4.10.0'
    chart: influxdb
    helm:
      values: |
        setDefaultUser:
          enabled: true
          user:
            existingSecret: influxdb-auth
        ingress:
          enabled: true
          tls: true
          secretName: influxdb-tls
          hostname: influxdb.itomm.pl
          annotations:
            kubernetes.io/ingress.class: nginx
            external-dns.alpha.kubernetes.io/hostname: influxdb.itomm.pl
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: tick
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true