apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kapacitor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tick
  source:
    path: ''
    repoURL: https://helm.influxdata.com/
    targetRevision: '1.3.1'
    chart: kapacitor
    helm:
      parameters:
        - name: influxURL
          value: http://influxdb:8086
        - name: existingSecret
          value: influxdb-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: tick
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true