apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tick
  source:
    path: ''
    repoURL: https://helm.influxdata.com/
    targetRevision: '1.8.4'
    chart: telegraf
    helm:
      values: |
        envFromSecret: "telegraf-secrets"
        env:
          - name: HOSTNAME
            value: "telegraf-polling-service"
        config:
          agent:
            interval: "10s"
            round_interval: true
            metric_batch_size: 1000
            metric_buffer_limit: 10000
            collection_jitter: "0s"
            flush_interval: "10s"
            flush_jitter: "0s"
            precision: ""
            debug: false
            quiet: false
            logfile: ""
            hostname: "$HOSTNAME"
            omit_hostname: false
          processors:
            - enum:
                mapping:
                  field: "status"
                  dest: "status_code"
                  value_mappings:
                    healthy: 1
                    problem: 2
                    critical: 3
          outputs:
            - influxdb:
                urls:
                  - ["$INFLUXDB_URL"]
                database: "$INFLUXDB_DB"
                username: "$INFLUXDB_USER"
                password: "$INFLUXDB_USER_PASSWORD"
          inputs:
            - statsd:
                service_address: ":8125"
                percentiles:
                  - 50
                  - 95
                  - 99
                metric_separator: "_"
                allowed_pending_messages: 10000
                percentile_limit: 1000

metrics:
  health:
    enabled: false
  collect_memstats: false

  destination:
    server: https://kubernetes.default.svc
    namespace: tick
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true