apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tick
  source:
    path: ''
    repoURL: https://helm.influxdata.com/
    targetRevision: '1.2.0'
    chart: telegraf-operator
    helm:
      values: |
      classes:
        secretName: "telegraf-operator-classes"
        default: "infra"
        data:
          infra: |
            [[outputs.influxdb]]
              urls = ["http://influxdb:8086"]
            [global_tags]
              env = "ci"
              hostname = "$HOSTNAME"
              nodename = "$NODENAME"
              type = "infra"
  destination:
    server: https://kubernetes.default.svc
    namespace: tick
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true